### ISSUE TITLE
Prepush test 008.test.Delegate_Seqs.sh fails

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/gems#69]
Specifically run_existingBuild_test()

My test output:
```
...

008.b Checking now that existing builds are found.

Test 008.b FAILED!
currentOutput:
/website/TESTS/git-ignore-me/pre-push/sequence/cb/Builds/effc5331-7f9e-4efa-b7d5-357d94afaa3b/Existing_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d/min-t5p.pdb

correctOutput:
correct_outputs/test008_output_subTest1.pdb

4 tests were attempted
3 tests passed 
4 were required
```

I noticed that my text editor does not show this file in the filetree display. It does show if I ls in the terminal. Unsure if that is related in any way.

I ran cmp manually to see the output:
```
webdev@danielwentworth-gw-grpc-delegator:/programs/gems/tests$ cmp /website/TESTS/git-ignore-me/pre-push/sequence/cb/Builds/effc5331-7f9e-4efa-b7d5-357d94afaa3b/Existing_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d/min-t5p.pdb correct_outputs/test008_output_subTest1.pdb
webdev@danielwentworth-gw-grpc-delegator:/programs/gems/tests$ 

```
To my understanding, if there was a difference, there would have been a msg similar to this:
```
~/dev/test:
$ cmp file1.txt file2.txt 
file1.txt file2.txt differ: char 1, line 1
```

I am therefore unsure why the test is failing.

**Comment by danwentworthart** [comment]
In case this is helpful:
```
webdev@danielwentworth-gw-grpc-delegator:/programs/gems/tests$ cmp /website/TESTS/git-ignore-me/pre-push/sequence/cb/Builds/effc5331-7f9e-4efa-b7d5-357d94afaa3b/Existing_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d/min-t5p.pdb correct_outputs/test008_output_subTest1.pdb
webdev@danielwentworth-gw-grpc-delegator:/programs/gems/tests$ echo $&
[1] 367

```

**Comment by danwentworthart** [comment]
The output of the test:
[caec5dc2-05f8-582a-b76a-f2be379ece8d.zip](https://github.com/GLYCAM-Web/gems/files/6909192/caec5dc2-05f8-582a-b76a-f2be379ece8d.zip)

**Comment by Lachele** [comment]
All I got in that zip was a symlink.  See below.  Do it again, but zip up everything starting at 'cb'.  Also, I think you meant to say 'echo $?' above, but no need to do it again. 

The "correct output" doesn't change between the first test and the second test.  So, maybe something in the symbolic linking isn't working as expected.  This might require a Zoom session so I can see your desktop, etc.

Here is what happened when I unzipped:

`lachele@pop-os:~/REPOS/GLYCAM_Dev_Env/V_2/Web_Programs/gems/tests/temp.dum$ unzip caec5dc2-05f8-582a-b76a-f2be379ece8d.zip `
`Archive:  caec5dc2-05f8-582a-b76a-f2be379ece8d.zip`
`    linking: caec5dc2-05f8-582a-b76a-f2be379ece8d  -> ../../../Sequences/00e7d454-06dd-5067-b6c9-441dd52db586/buildStrategyID1/All_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d `
`finishing deferred symbolic links:`
`  caec5dc2-05f8-582a-b76a-f2be379ece8d -> ../../../Sequences/00e7d454-06dd-5067-b6c9-441dd52db586/buildStrategyID1/All_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d`
`lachele@pop-os:~/REPOS/GLYCAM_Dev_Env/V_2/Web_Programs/gems/tests/temp.dum$ ls -l`
`total 8`
`lrwxrwxrwx 1 lachele lachele 120 Jul 31 00:56 caec5dc2-05f8-582a-b76a-f2be379ece8d -> ../../../Sequences/00e7d454-06dd-5067-b6c9-441dd52db586/buildStrategyID1/All_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d`
`-rw-rw-r-- 1 lachele lachele 354 Jul 31 00:55 caec5dc2-05f8-582a-b76a-f2be379ece8d.zip`

..that is, I just get a symbolic link that references something that doesn't exist.  And, I wonder if there might be some Mac thing that causes the symlinks to be handled differently.

**Comment by Lachele** [comment]
[For other readers, Dan and I talked about this today and he is checking to see if some setting in his computer and/or Docker is interfering.  Currently, this appears to be specific to Docker on Mac.]

If you don't find an obvious issue in the settings, you might try sending the output from the two comparisons (lines 40 and 55) to unique files rather than to /dev/null.  You can inspect the files later to see if they give useful info.

Also consider sending output to 'out1.json' and 'out2.json' on lines 22 ad 52.  The rm statements a few lines later in each case will fail.  Change the filename there, but comment them out while testing.  A 'pass' might still give useful info in the output.

**Comment by danwentworthart** [comment]
A couple details are leading me to suspect that it is not related to Docker settings. 
1. When I run all the tests on the desktop, the previous test is passed in 80 seconds. Things are moving along faster.
2. I systematically echo out each element of the path for currentOutput, and it fails to find the folder named after the conformerID. This keeps drawing me back into questioning the symlink. But I want to try the suggestions you gave, and see if I can find more proof of a specific suspect.

**Comment by Lachele** [comment]
I'm going to write a special test for you that does a lot of over-the-top checking of everything.  

Unless you say not to, I will require you to retain the output you normally get from the first of the two tests.  That part seems to be working, so there's no point making you wait through it.  It might take me a little while to write it.

**Comment by Lachele** [comment]
While I'm writing...  clear the gems logs and run the test.  Then, look for vomit in the debug log.  Let me know if you find anything.

**Comment by danwentworthart** [comment]
Issue is specific to the symbolic link. Here's my verbose output:

Checking now that existing builds are found.

pUUID: dc216f5a-1c90-4d2a-a921-bb36d3a8fe38
conformerID: caec5dc2-05f8-582a-b76a-f2be379ece8d
currentOutput: /website/TESTS/git-ignore-me/pre-push/sequence/cb/Builds/dc216f5a-1c90-4d2a-a921-bb36d3a8fe38/Existing_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d/min-t5p.pdb
Test FAILED!
compared /website/TESTS/git-ignore-me/pre-push/sequence/cb/Builds/dc216f5a-1c90-4d2a-a921-bb36d3a8fe38/Existing_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d/min-t5p.pdb
to       correct_outputs/test008_output_subTest1.pdb
cmp: /website/TESTS/git-ignore-me/pre-push/sequence/cb/Builds/dc216f5a-1c90-4d2a-a921-bb36d3a8fe38/Existing_Builds/caec5dc2-05f8-582a-b76a-f2be379ece8d/min-t5p.pdb: No such file or directory

found the project dir: /website/TESTS/git-ignore-me/pre-push/sequence/cb/Builds/dc216f5a-1c90-4d2a-a921-bb36d3a8fe38/ 
found the Existing_Builds dir: /website/TESTS/git-ignore-me/pre-push/sequence/cb/Builds/dc216f5a-1c90-4d2a-a921-bb36d3a8fe38/Existing_Builds/
conformerId dir does not exist.

4 tests were attempted
3 tests passed 
4 were required

**Comment by danwentworthart** [comment]
I can confirm that the symbolic link does exist. However, I wonder if the issue is that a symbolic link is technically a file, so are we comparing the content of our correct output file to the content of the symbolic link file, rather than the content of the file pointed to by the symbolic link?

**Comment by danwentworthart** [comment]
I have pushed the fix to this.
