### ISSUE TITLE
Change API interaction between website and sequence entity

### ISSUE THREAD

**Issue by Lachele** [GLYCAM-Web/gems#74]
This is something to do when we refactor the Sequence entity.

The current way the website interfaces the sequence entity is the result of various workarounds for problems that no longer exist.  The current interface means that the sequence entity code contains some tortured logic.  These changes will make the code better.

If someone thinks of better changes than these, then let those override these.  Draft code exists. See below.

Specifically, these are the changes I'd like to see:

- When requesting an evaluation, call it that.  Stop calling it a build. 
    - To facilitate this, add a "buildDefaultStructure" option to the Evaluation Options.   Set to true by default.
- Set mdMinimize to True unless there is good reason not to
- The unminimized structure will be generated at the start as always unless buildDefaultStructure is set to false.
- The project ID that comes back after the build request will ALWAYS be different from the evaluation request.
    - It should be possible to override this, but the default should be to always make a new project.
    - This keeps a user's project from being littered with default structures that the user didn't request.
- Set a symbolic link inside the Sequence directory to the default structure's directory.  
    - Doing this means that a default 3D structure can be displayed without making a project or evaluation.

I made most of these changes in GEMS while I was working on https://github.com/GLYCAM-Web/website/issues/128 
The changes are in the fix-multi-structure-bug branch of GEMS.  As soon as I realized that the fix was actually in GMML, I abandoned these changes (because of the additional work that would be required of myself and others).

**Comment by Lachele** [comment]
Oh... nevermind.  I will have to do it now because of https://github.com/GLYCAM-Web/website/issues/128

I'll update this comment with anything leftover when we finish fixing the bug or close it if it's all done.

**Comment by gitoliver** [comment]
We've adapted the website to the changes made in gems and fixed the bugs. 

>  When requesting an evaluation, call it that. Stop calling it a build.
The website does this now. Our docs are likely out of date.    

> To facilitate this, add a "buildDefaultStructure" option to the Evaluation Options. Set to true by default.

I've not tested setting this to false. Will likely cause a fire.

>     Set mdMinimize to True unless there is good reason not to

Default is True and I've not tested setting it to false. Will likely cause a fire.

> The unminimized structure will be generated at the start as always unless buildDefaultStructure is set to false.

Yes.

> The project ID that comes back after the build request will ALWAYS be different from the evaluation request.
>         It should be possible to override this, but the default should be to always make a new project.
>         This keeps a user's project from being littered with default structures that the user didn't request.

Done. I did not test trying to override this...

> Set a symbolic link inside the Sequence directory to the default structure's directory.
>         Doing this means that a default 3D structure can be displayed without making a project or evaluation.

This is working.

Evidence here: https://youtu.be/_viGpCu_mZw?si=N2O2Zr2MgZZbufyV

Nothing further should be done to change the behavior of the current sequence module in gemsModules/deprecated/ . It needs a re-write. I'm going to make a new post with the known problems I'm not touching.
